Repository DeveloperAcademy-POSTECH/MC3-Team6-UDD, pull requests merged in 2022-08, with the labels that each got.

#56 [Feat] 좋아요 목록 페이지 구현
  UDD.xcodeproj/project.pbxproj
  UDD/Presentation/Main/Models/OpponentDogLikeDataModel.swift
  UDD/Presentation/Main/View/Like/Like.storyboard
  UDD/Presentation/Main/View/Like/LikeListView.swift
  UDD/Presentation/Main/View/Like/SubViews/LikeTableViewCell.swift
  UDD/Presentation/Main/View/Like/SubViews/LikeTableViewCell.xib
Labels: ✨ Feature

#64 린트 오류 제거
  UDD/Presentation/OnBoarding/View/AddDogDetail/AddDogDetailController.swift
  UDD/Presentation/OnBoarding/View/LoginScreen/LoginScreenController.swift
Labels: :hammer: Refactor

#66 필터 뷰 해제 시 메인 뷰로 노티
  UDD/Presentation/Main/View/Home/HomeViewController.swift
  UDD/Presentation/Main/View/Home/SubViews/FilterTagViewController.swift
Labels: ✨ Feature, :hammer: Refactor

#65 [Feat] 견주 정보 입력 View UI 수정
  UDD/Presentation/OnBoarding/View/AddUserData/AddUserData.storyboard
Labels: ✨ Feature, :hammer: Refactor

#68 Feat/link onboarding
  UDD/Presentation/OnBoarding/View/AddDogDetail/AddDogDetail.storyboard
  UDD/Presentation/OnBoarding/View/AddDogDetail/AddDogDetailController.swift
Labels: ✨ Feature, :hammer: Refactor

#72 잡다한 오류 수정
  UDD.xcodeproj/project.pbxproj
  UDD/Presentation/Main/View/Home/HomeViewController.swift
  UDD/Presentation/Main/View/Home/SubViews/PostTableViewCell.swift
  UDD/Presentation/Main/View/Home/SubViews/PostTableViewCell.xib
  UDD/Presentation/Main/View/Like/LikeListView.swift
Labels: :hammer: Refactor, :fire: HotFix

#70 TextField Underline 수정
  UDD/Presentation/OnBoarding/View/AddDogDetail/AddDogDetail.storyboard
  UDD/Presentation/OnBoarding/View/AddUserData/AddUserData.storyboard
  UDD/Presentation/OnBoarding/View/LoginScreen/LoginScreen.storyboard
  UDD/Presentation/Others/View/CustomTextField.swift
Labels: :hammer: Refactor

#75 네비게이션 뷰 이동 한 후, 필터 버튼 작동 안하는 문제 해결
  UDD/Presentation/Main/View/Home/HomeViewController.swift
Labels: :fire: HotFix

#76 Update README.md
  README.md
Labels: :page_facing_up: Docs

#73 Second Sprint
  .swiftlint.yml
  UDD.xcodeproj/project.pbxproj
  UDD/Application/Assets.xcassets/AccentColor.colorset/Contents.json
  UDD/Application/Assets.xcassets/FemaleColor.colorset/Contents.json
  UDD/Application/Assets.xcassets/MaleColor.colorset/Contents.json
  UDD/Application/Assets.xcassets/NeuterColor.colorset/Contents.json
  UDD/Application/Assets.xcassets/mybox.imageset/Contents.json
  UDD/Application/Assets.xcassets/mybox.imageset/mybox.png
  UDD/Application/Assets.xcassets/yourBox.imageset/Contents.json
  UDD/Application/Assets.xcassets/yourBox.imageset/yourBox.png
  UDD/Application/Info.plist
  UDD/Application/SceneDelegate.swift
  UDD/Presentation/Headers/CustomSPCDetent-Bridging-Header.h
  UDD/Presentation/Headers/UISheetPresentationControllerDetent+Private.h
  UDD/Presentation/Main/Models/DefaultTagModel.swift
  UDD/Presentation/Main/Models/DogOwner.swift
  UDD/Presentation/Main/Models/OpponentDogLikeDataModel.swift
  UDD/Presentation/Main/View/Chat/Chat.storyboard
  UDD/Presentation/Main/View/Chat/ChatListController.swift
  UDD/Presentation/Main/View/ChatRoom/ChatInfoCell.swift
  UDD/Presentation/Main/View/ChatRoom/ChatInfoCell.xib
  UDD/Presentation/Main/View/ChatRoom/ChatRoom.storyboard
  UDD/Presentation/Main/View/ChatRoom/ChatRoomVC.swift
  UDD/Presentation/Main/View/ChatRoom/MyCell.swift
  UDD/Presentation/Main/View/ChatRoom/MyCell.xib
  UDD/Presentation/Main/View/ChatRoom/YourCell.swift
  UDD/Presentation/Main/View/ChatRoom/YourCell.xib
  UDD/Presentation/Main/View/Home/Home.storyboard
  UDD/Presentation/Main/View/Home/HomeViewController.swift
  UDD/Presentation/Main/View/Home/SubViews/FilterTagViewController.swift
  UDD/Presentation/Main/View/Home/SubViews/PostTableViewCell.swift
  UDD/Presentation/Main/View/Home/SubViews/PostTableViewCell.xib
  UDD/Presentation/Main/View/HomeDetailView/HomeDetailView.storyboard
  UDD/Presentation/Main/View/HomeDetailView/HomeDetailViewController.swift
  UDD/Presentation/Main/View/Like/Like.storyboard
  UDD/Presentation/Main/View/Like/LikeListView.swift
  UDD/Presentation/Main/View/Like/SubViews/LikeTableViewCell.swift
  UDD/Presentation/Main/View/Like/SubViews/LikeTableViewCell.xib
  UDD/Presentation/Main/View/Profile/Profile.storyboard
  UDD/Presentation/Main/View/TabBar.storyboard
  UDD/Presentation/Main/View/TabBarController.swift
  UDD/Presentation/OnBoarding/View/AddDogDetail/AddDogDetail.storyboard
  UDD/Presentation/OnBoarding/View/AddDogDetail/AddDogDetailController.swift
  UDD/Presentation/OnBoarding/View/AddDogName/AddDogName.storyboard
  UDD/Presentation/OnBoarding/View/AddUserData/AddUserData.storyboard
  UDD/Presentation/OnBoarding/View/AddUserData/AddUserDataViewController.swift
  UDD/Presentation/OnBoarding/View/LoginScreen/LoginScreen.storyboard
  UDD/Presentation/OnBoarding/View/LoginScreen/LoginScreenController.swift
  UDD/Presentation/OnBoarding/View/SelectTag/SelectTag.storyboard
  UDD/Presentation/OnBoarding/View/StartScreen/StartNaviController.swift
  UDD/Presentation/OnBoarding/View/StartScreen/StartScreen.storyboard
  UDD/Presentation/Others/Onboarding/Storage.swift
  UDD/Presentation/Others/View/CustomTextField.swift
  UDD/Presentation/Others/View/Extention_UIView.swift
  UDD/Presentation/Others/View/LineView.swift
Labels: ✨ Feature
