Repository DeveloperAcademy-POSTECH/MC3-Team6-UDD, pull requests merged in 2022-07, with the labels that each got.

#6 Update README.md
  README.md
Labels: :page_facing_up: Docs

#7 update README.md
  README.md
Labels: :page_facing_up: Docs

#10 Fix xcodeproj can't build issue
  UDD.xcodeproj/project.pbxproj
  UDD.xcodeproj/xcuserdata/mjkim.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: 🤖 Chore

#11 Delete Cocoapods xcworkspace
  .gitattributes
  UDD.xcodeproj/xcshareddata/xcschemes/UDD.xcscheme
  UDD.xcodeproj/xcuserdata/mjkim.xcuserdatad/xcschemes/xcschememanagement.plist
  UDD.xcworkspace/contents.xcworkspacedata
  UDD.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: 🤖 Chore

#13 #12 Add Tab Bar
  UDD.xcodeproj/project.pbxproj
  UDD/Assets.xcassets/AccentColor.colorset/Contents.json
  UDD/Assets.xcassets/AppIcon.appiconset/Contents.json
  UDD/Base.lproj/Main.storyboard
  UDD/ViewControllers/ViewController.swift
  UDD/Views/Base.lproj/Main.storyboard
  UDD/Views/Chat.storyboard
  UDD/Views/Home.storyboard
  UDD/Views/Like.storyboard
Labels: ✨ Feature

#15 [feat][refactor] #14 파일구조 변경 및 커스텀 텍스트바 구현
  UDD.xcodeproj/project.pbxproj
  UDD/Application/AppDelegate.swift
  UDD/Application/Assets.xcassets/AccentColor.colorset/Contents.json
  UDD/Application/Assets.xcassets/AppIcon.appiconset/Contents.json
  UDD/Application/Assets.xcassets/Contents.json
  UDD/Application/Info.plist
  UDD/Application/SceneDelegate.swift
  UDD/Presentation/Home/View/Base.lproj/Main.storyboard
  UDD/Presentation/Home/View/Chat.storyboard
  UDD/Presentation/Home/View/Home.storyboard
  UDD/Presentation/Home/View/Like.storyboard
  UDD/Presentation/Others/ViewController/CustomTextField.swift
Labels: ✨ Feature, :hammer: Refactor

#19 #17 Info.plist 경로 변경으로 빌드 오류 발생 이슈 해결
  .swiftlint.yml
  UDD.xcodeproj/project.pbxproj
  UDD/Presentation/Main/View/Base.lproj/TabBar.storyboard
  UDD/Presentation/Main/View/Chat.storyboard
  UDD/Presentation/Main/View/Home.storyboard
  UDD/Presentation/Main/View/Like.storyboard
  UDD/Presentation/Others/ViewController/CustomTextField.swift
  UDD/ViewControllers/ViewController.swift
Labels: :lady_beetle: Bug, :fire: HotFix

#20 README.md에 bugfix branch 컨벤션 추가
  README.md
Labels: :page_facing_up: Docs

#30 #30 TextView 기능 구현
  UDD.xcodeproj/project.pbxproj
  UDD/Presentation/Others/ViewController/IntroductionTextView.swift
Labels: ✨ Feature

#38 Feat/select tag UI
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/TTGTagCollectionView/LICENSE
  Pods/TTGTagCollectionView/README.md
  Pods/TTGTagCollectionView/Sources/TTGTagCollectionView-Bridging-Header.h
  Pods/TTGTagCollectionView/Sources/TTGTagCollectionView.h
  Pods/TTGTagCollectionView/Sources/TTGTagCollectionView.m
  Pods/TTGTagCollectionView/Sources/TTGTextTag.h
  Pods/TTGTagCollectionView/Sources/TTGTextTag.m
  Pods/TTGTagCollectionView/Sources/TTGTextTagAttributedStringContent.h
  Pods/TTGTagCollectionView/Sources/TTGTextTagAttributedStringContent.m
  Pods/TTGTagCollectionView/Sources/TTGTextTagCollectionView.h
  Pods/TTGTagCollectionView/Sources/TTGTextTagCollectionView.m
  Pods/TTGTagCollectionView/Sources/TTGTextTagContent.h
  Pods/TTGTagCollectionView/Sources/TTGTextTagContent.m
  Pods/TTGTagCollectionView/Sources/TTGTextTagStringContent.h
  Pods/TTGTagCollectionView/Sources/TTGTextTagStringContent.m
  Pods/TTGTagCollectionView/Sources/TTGTextTagStyle.h
  Pods/TTGTagCollectionView/Sources/TTGTextTagStyle.m
  Pods/Target Support Files/Pods-UDD/Pods-UDD-acknowledgements.markdown
  Pods/Target Support Files/Pods-UDD/Pods-UDD-acknowledgements.plist
  Pods/Target Support Files/Pods-UDD/Pods-UDD-frameworks-Debug-input-files.xcfilelist
  Pods/Target Support Files/Pods-UDD/Pods-UDD-frameworks-Debug-output-files.xcfilelist
  Pods/Target Support Files/Pods-UDD/Pods-UDD-frameworks-Release-input-files.xcfilelist
  Pods/Target Support Files/Pods-UDD/Pods-UDD-frameworks-Release-output-files.xcfilelist
  Pods/Target Support Files/Pods-UDD/Pods-UDD-frameworks.sh
  Pods/Target Support Files/Pods-UDD/Pods-UDD.debug.xcconfig
  Pods/Target Support Files/Pods-UDD/Pods-UDD.release.xcconfig
  Pods/Target Support Files/TTGTagCollectionView/TTGTagCollectionView-Info.plist
  Pods/Target Support Files/TTGTagCollectionView/TTGTagCollectionView-dummy.m
  Pods/Target Support Files/TTGTagCollectionView/TTGTagCollectionView-prefix.pch
  Pods/Target Support Files/TTGTagCollectionView/TTGTagCollectionView-umbrella.h
  Pods/Target Support Files/TTGTagCollectionView/TTGTagCollectionView.debug.xcconfig
  Pods/Target Support Files/TTGTagCollectionView/TTGTagCollectionView.modulemap
  Pods/Target Support Files/TTGTagCollectionView/TTGTagCollectionView.release.xcconfig
  UDD.xcodeproj/project.pbxproj
  UDD.xcworkspace/contents.xcworkspacedata
  UDD/Presentation/OnBoarding/View/SelectTag.storyboard
  UDD/Presentation/OnBoarding/ViewController/SelectTagViewController.swift
Labels: ✨ Feature

#40 견주 정보 입력 UI
  UDD.xcodeproj/project.pbxproj
  UDD/Application/Info.plist
  UDD/Presentation/OnBoarding/View/AddUserData.storyboard
  UDD/Presentation/OnBoarding/ViewController/AddUserDataViewController.swift
Labels: ✨ Feature

#41 Feat/home detail view
  UDD.xcodeproj/project.pbxproj
  UDD/Application/Assets.xcassets/dogicon.imageset/Contents.json
  UDD/Application/Assets.xcassets/dogicon.imageset/dogicon.png
  UDD/Application/Assets.xcassets/golddog.imageset/Contents.json
  UDD/Application/Assets.xcassets/golddog.imageset/golddog.jpeg
  UDD/Application/Info.plist
  UDD/Presentation/Main/View/DogOwner.swift
  UDD/Presentation/Main/View/Extention_UIView.swift
  UDD/Presentation/Main/View/HomeDetailView.storyboard
  UDD/Presentation/Main/View/HomeDetailViewController.swift
Labels: ✨ Feature

#42 홈 화면 구현
  .swiftlint.yml
  Pods/Pods.xcodeproj/project.pbxproj
  UDD.xcodeproj/project.pbxproj
  UDD/Application/Info.plist
  UDD/Presentation/Main/Models/DogDataModel.swift
  UDD/Presentation/Main/Models/DogOwner.swift
  UDD/Presentation/Main/View/Chat/Chat.storyboard
  UDD/Presentation/Main/View/Home.storyboard
  UDD/Presentation/Main/View/Home/Home.storyboard
  UDD/Presentation/Main/View/Home/HomeViewController.swift
  UDD/Presentation/Main/View/Home/SubViews/PostTableViewCell.swift
  UDD/Presentation/Main/View/Home/SubViews/PostTableViewCell.xib
  UDD/Presentation/Main/View/HomeDetailView/HomeDetailView.storyboard
  UDD/Presentation/Main/View/HomeDetailView/HomeDetailViewController.swift
  UDD/Presentation/Main/View/Like/Like.storyboard
  UDD/Presentation/OnBoarding/View/AddDogName/AddDogName.storyboard
  UDD/Presentation/OnBoarding/View/AddDogName/AddDogNameViewController.swift
  UDD/Presentation/OnBoarding/View/AddUserData/AddUserData.storyboard
  UDD/Presentation/OnBoarding/View/AddUserData/AddUserDataViewController.swift
  UDD/Presentation/OnBoarding/View/LoginScreen.storyboard
  UDD/Presentation/OnBoarding/View/LoginScreen/LoginScreen.storyboard
  UDD/Presentation/OnBoarding/View/LoginScreen/LoginScreenController.swift
  UDD/Presentation/OnBoarding/View/SelectTag/SelectTag.storyboard
  UDD/Presentation/OnBoarding/View/SelectTag/SelectTagViewController.swift
  UDD/Presentation/OnBoarding/View/StartScreen.storyboard
  UDD/Presentation/OnBoarding/View/StartScreen/StartScreen.storyboard
  UDD/Presentation/OnBoarding/View/StartScreen/StartScreenController.swift
  UDD/Presentation/OnBoarding/ViewController/LoginScreenController.swift
  UDD/Presentation/OnBoarding/ViewController/StartScreenController.swift
  UDD/Presentation/Others/View/CustomTextField.swift
  UDD/Presentation/Others/View/Extention_UIView.swift
  UDD/Presentation/Others/View/IntroductionTextView.swift
Labels: ✨ Feature

#45 Feat/home detail view 수정사항 반영
  UDD.xcodeproj/project.pbxproj
  UDD/Presentation/Main/Models/DogDataModel.swift
  UDD/Presentation/Main/Models/DogOwner.swift
  UDD/Presentation/Main/View/HomeDetailView/HomeDetailView.storyboard
  UDD/Presentation/Main/View/HomeDetailView/HomeDetailViewController.swift
Labels: ✨ Feature

#49 Feat/chat list
  UDD.xcodeproj/project.pbxproj
  UDD/Presentation/Main/View/Chat/Chat.storyboard
  UDD/Presentation/Main/View/Chat/ChatListController.swift
  UDD/Presentation/Main/View/Home/Home.storyboard
Labels: ✨ Feature

#46 Home 화면
  UDD.xcodeproj/project.pbxproj
  UDD/Application/Assets.xcassets/AccentColor.colorset/Contents.json
  UDD/Application/Assets.xcassets/FemaleColor.colorset/Contents.json
  UDD/Application/Assets.xcassets/MaleColor.colorset/Contents.json
  UDD/Application/Assets.xcassets/NeuterColor.colorset/Contents.json
  UDD/Presentation/Main/View/Home/Home.storyboard
  UDD/Presentation/Main/View/Home/HomeViewController.swift
  UDD/Presentation/Main/View/Home/SubViews/PostTableViewCell.swift
  UDD/Presentation/Main/View/Home/SubViews/PostTableViewCell.xib
  UDD/Presentation/Main/View/HomeDetailView/HomeDetailViewController.swift
  UDD/Presentation/Main/View/Profile/Profile.storyboard
  UDD/Presentation/Main/View/TabBar.storyboard
  UDD/Presentation/Others/View/Extention_UIView.swift
Labels: ✨ Feature

#52 Feat/chat room
  UDD.xcodeproj/project.pbxproj
  UDD/Application/Assets.xcassets/mybox.imageset/Contents.json
  UDD/Application/Assets.xcassets/mybox.imageset/mybox.png
  UDD/Application/Assets.xcassets/yourBox.imageset/Contents.json
  UDD/Application/Assets.xcassets/yourBox.imageset/yourBox.png
  UDD/Presentation/Main/View/ChatRoom/ChatRoom.storyboard
  UDD/Presentation/Main/View/ChatRoom/ChatRoomVC.swift
  UDD/Presentation/Main/View/ChatRoom/MyCell.swift
  UDD/Presentation/Main/View/ChatRoom/MyCell.xib
  UDD/Presentation/Main/View/ChatRoom/YourCell.swift
  UDD/Presentation/Main/View/ChatRoom/YourCell.xib
Labels: ✨ Feature

#55 [Feat] 필터링 뷰 및 태그 선택 구현 완료
  .swiftlint.yml
  UDD.xcodeproj/project.pbxproj
  UDD.xcworkspace/contents.xcworkspacedata
  UDD/Presentation/Headers/CustomSPCDetent-Bridging-Header.h
  UDD/Presentation/Headers/UISheetPresentationControllerDetent+Private.h
  UDD/Presentation/Main/Models/DefaultTagModel.swift
  UDD/Presentation/Main/View/ChatRoom/ChatRoomVC.swift
  UDD/Presentation/Main/View/Home/HomeViewController.swift
  UDD/Presentation/Main/View/Home/SubViews/FilterTagViewController.swift
  UDD/Presentation/Others/View/LineView.swift
Labels: ✨ Feature

#58 Feat/chat rooms
  UDD.xcodeproj/project.pbxproj
  UDD/Presentation/Main/View/Chat/Chat.storyboard
  UDD/Presentation/Main/View/Chat/ChatListController.swift
  UDD/Presentation/Main/View/ChatRoom/ChatInfoCell.swift
  UDD/Presentation/Main/View/ChatRoom/ChatInfoCell.xib
  UDD/Presentation/Main/View/ChatRoom/ChatRoom.storyboard
  UDD/Presentation/Main/View/ChatRoom/ChatRoomVC.swift
Labels: ✨ Feature, :hammer: Refactor

#57 Refactor/home detail view
  UDD/Presentation/Main/Models/DogDataModel.swift
  UDD/Presentation/Main/View/Home/HomeViewController.swift
  UDD/Presentation/Main/View/HomeDetailView/HomeDetailView.storyboard
  UDD/Presentation/Main/View/HomeDetailView/HomeDetailViewController.swift
Labels: ✨ Feature, :hammer: Refactor

#60 [feat] send chatRoom data to chatList & refactor
  UDD/Presentation/Main/View/Chat/ChatListController.swift
  UDD/Presentation/Main/View/ChatRoom/ChatInfoCell.swift
  UDD/Presentation/Main/View/ChatRoom/ChatInfoCell.xib
  UDD/Presentation/Main/View/ChatRoom/ChatRoomVC.swift
Labels: ✨ Feature, :hammer: Refactor

#61 Feat/link onboarding
  UDD.xcodeproj/project.pbxproj
  UDD.xcworkspace/contents.xcworkspacedata
  UDD/Application/Info.plist
  UDD/Application/SceneDelegate.swift
  UDD/Presentation/Main/View/Home/Home.storyboard
  UDD/Presentation/Main/View/TabBar.storyboard
  UDD/Presentation/Main/View/TabBarController.swift
  UDD/Presentation/OnBoarding/View/AddDogDetail/AddDogDetail.storyboard
  UDD/Presentation/OnBoarding/View/AddDogDetail/AddDogDetailController.swift
  UDD/Presentation/OnBoarding/View/AddDogName/AddDogName.storyboard
  UDD/Presentation/OnBoarding/View/AddUserData/AddUserData.storyboard
  UDD/Presentation/OnBoarding/View/AddUserData/AddUserDataViewController.swift
  UDD/Presentation/OnBoarding/View/LoginScreen/LoginScreen.storyboard
  UDD/Presentation/OnBoarding/View/LoginScreen/LoginScreenController.swift
  UDD/Presentation/OnBoarding/View/SelectTag/SelectTag.storyboard
  UDD/Presentation/OnBoarding/View/StartScreen/StartNaviController.swift
  UDD/Presentation/OnBoarding/View/StartScreen/StartScreen.storyboard
  UDD/Presentation/Others/Onboarding/Storage.swift
Labels: ✨ Feature
